create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  organization text,
  phone text not null,
  email text not null,
  service text not null,
  message text not null
);

alter table public.inquiries enable row level security;

drop policy if exists "public can submit inquiries" on public.inquiries;
create policy "public can submit inquiries" on public.inquiries
for insert to anon, authenticated with check (true);

drop policy if exists "admins can read inquiries" on public.inquiries;
create policy "admins can read inquiries" on public.inquiries
for select to authenticated using (auth.uid() is not null);
