import React, { useEffect, useState } from 'react';
import { supabase, hasSupabase } from '../lib/supabase';

export default function Admin(){
 const [session,setSession]=useState(null), [items,setItems]=useState([]), [email,setEmail]=useState(''), [password,setPassword]=useState(''), [msg,setMsg]=useState('');
 const load=async()=>{ if(!supabase)return; const {data,error}=await supabase.from('inquiries').select('*').order('created_at',{ascending:false}); if(error)setMsg(error.message); else setItems(data||[]); };
 useEffect(()=>{ if(!supabase)return; supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>subscription.unsubscribe(); },[]);
 useEffect(()=>{if(session)load()},[session]);
 const login=async(e)=>{e.preventDefault();setMsg('');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);else setSession(data.session)};
 const logout=async()=>{await supabase.auth.signOut();setSession(null)};
 const changeCredentials=async(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const nextEmail=fd.get('newEmail');const p=fd.get('newPassword');const {error}=await supabase.auth.updateUser({email:nextEmail || undefined,password:p || undefined});setMsg(error?error.message:'Admin credentials updated. Check email if Supabase asks for confirmation.');e.currentTarget.reset();};
 if(!hasSupabase)return <section className="page-pad inner-page"><div className="page-title"><span className="section-no">ADMIN</span><h1>Database not<br /><em>configured.</em></h1><p>Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env, then run the app again.</p></div></section>;
 if(!session)return <section className="page-pad inner-page admin-page"><div className="page-title"><span className="section-no">09 / ADMIN LOGIN</span><h1>Private<br /><em>control room.</em></h1><p>Admin access is handled by Supabase Authentication.</p></div><form className="admin-login" onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required /></label><button className="btn btn-dark">Login ↗</button>{msg&&<div className="form-status">{msg}</div>}</form></section>;
 return <section className="page-pad inner-page admin-page"><div className="admin-head"><div><span className="section-no">09 / ADMIN</span><h1>Inquiry<br /><em>dashboard.</em></h1></div><button className="btn btn-dark" onClick={logout}>Logout</button></div><div className="admin-tools"><div><strong>Signed in:</strong> {session.user.email}</div><form onSubmit={changeCredentials} className="password-form"><input name="newEmail" type="email" required placeholder="Admin email" defaultValue={session.user.email}/><input name="newPassword" type="password" minLength="8" required placeholder="New password"/><button className="btn">Update Login</button></form></div>{msg&&<div className="form-status">{msg}</div>}<div className="inquiry-table"><div className="inquiry-head"><span>Name</span><span>Organisation</span><span>Service</span><span>Contact</span><span>Date</span></div>{items.map(i=><article key={i.id}><span>{i.name}</span><span>{i.organization||'—'}</span><span>{i.service}</span><span>{i.email}<br/>{i.phone}</span><span>{new Date(i.created_at).toLocaleString()}</span></article>)}{!items.length&&<p className="empty-state">No inquiries yet.</p>}</div></section>
}
